### ISSUE TITLE
Can I record commands without EasyVR Commander?

### ISSUE THREAD

**Issue by kevinxh** [RoboTech-srl/EasyVR-Arduino#5]
Hi,

Thanks for making this library, my question is: Can I record commands without EasyVR Commander?

I want to write code to control the device to record commands. But I can't find tutorials for that.

Thanks!

**Comment by ppescher** [comment]
Yes! Using this library you can do everything the EasyVR Commander does, they use the same communication protocol.

If your command structure does not change, as it is usually the case, you can pre-create commands using the EasyVR Commander and then manage training of each command with this library.

See the methods:
* dumpCommand() to retrieve the training status of a command
* trainCommand() to record a new training (call at least twice per command)
* eraseCommand() to remove training data from a command

You can download a full Arduino demo, from http://www.veear.eu/downloads/ (look for the "EasyVR Home Automation" demo and video)
